[package]
name = "brainfuck_interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.49"
inquire = "0.9.1"
thiserror = "2.0.17"

[dev-dependencies]
assert_cmd = "2.0.17"
expectrl = "0.8.0"
predicates = "3.1.3"

[[bin]]
name = "braincrab"
path = "src/main.rs"
